In [79]:
#make a list of the vocabulary: all the distinct words occuring in the train set 

import csv

allwords = []
with open("train.tsv", encoding="utf8") as tsvfile:    #open training set
    lines = csv.reader(tsvfile, delimiter="\t")        #convert file to lines
    for line in lines:
        statement = line[2]                                #get statement from each line 
        lostrings = statement.split(" ")                   #convert string to list of strings
        allwords.extend(lostrings)

vocab = []                          #initialize a list for all the distint words in the trainset
for word in allwords:
    if word in vocab:               #do not add word if word is already in vocabulary 
        continue 
    else:
        vocab.append(word)


print("Number of words in trainset:", len(allwords))
print("Number of distinct words in trainset:", len(vocab))
print(allwords[:25])
print(vocab[:25])

Number of words in trainset: 184014
Number of distinct words in trainset: 21650
['Says', 'the', 'Annies', 'List', 'political', 'group', 'supports', 'third-trimester', 'abortions', 'on', 'demand.', 'When', 'did', 'the', 'decline', 'of', 'coal', 'start?', 'It', 'started', 'when', 'natural', 'gas', 'took', 'off']
['Says', 'the', 'Annies', 'List', 'political', 'group', 'supports', 'third-trimester', 'abortions', 'on', 'demand.', 'When', 'did', 'decline', 'of', 'coal', 'start?', 'It', 'started', 'when', 'natural', 'gas', 'took', 'off', 'that']


In [83]:
#make a list containing all the statements and count number of statements 

statements = []

with open("train.tsv", encoding="utf8") as tsvfile:
    tsvreader = csv.reader(tsvfile, delimiter="\t")
    for line in tsvreader:
        aline = line[2]
        bline = aline.split(" ")
        statements.append(bline)


countlines = len(statements)
print("Number of statements:", countlines)
print("First 3 statements:", statements[:3])

Number of statements: 10240
First 3 statements: [['Says', 'the', 'Annies', 'List', 'political', 'group', 'supports', 'third-trimester', 'abortions', 'on', 'demand.'], ['When', 'did', 'the', 'decline', 'of', 'coal', 'start?', 'It', 'started', 'when', 'natural', 'gas', 'took', 'off', 'that', 'started', 'to', 'begin', 'in', '(President', 'George', 'W.)', 'Bushs', 'administration.'], ['Hillary', 'Clinton', 'agrees', 'with', 'John', 'McCain', '"by', 'voting', 'to', 'give', 'George', 'Bush', 'the', 'benefit', 'of', 'the', 'doubt', 'on', 'Iran."']]


In [92]:
#this list is similar to the previous list but it contains the label (true/false) at beginning of eacht statement 
statements = []

with open("train.tsv", encoding="utf8") as tsvfile:
    tsvreader = csv.reader(tsvfile, delimiter="\t")
    for line in tsvreader:
        aline = line[2]
        label = line[1]
        bline = aline.split(" ")
        bline.insert(0, label)
        statements.append(bline)


countlines = len(statements)
print("Number of statements:", countlines)
print("First 3 statements:", statements[:3])

Number of statements: 10240
First 3 statements: [['false', 'Says', 'the', 'Annies', 'List', 'political', 'group', 'supports', 'third-trimester', 'abortions', 'on', 'demand.'], ['half-true', 'When', 'did', 'the', 'decline', 'of', 'coal', 'start?', 'It', 'started', 'when', 'natural', 'gas', 'took', 'off', 'that', 'started', 'to', 'begin', 'in', '(President', 'George', 'W.)', 'Bushs', 'administration.'], ['mostly-true', 'Hillary', 'Clinton', 'agrees', 'with', 'John', 'McCain', '"by', 'voting', 'to', 'give', 'George', 'Bush', 'the', 'benefit', 'of', 'the', 'doubt', 'on', 'Iran."']]


In [76]:
import numpy as np

labels ={"false":0, "barely-true":1,"half-true":2,"mostly-true":3,"true":4}

rows = countlines
columns = len(vocab) + 1 #add one for the statement 
matrix = np.zeros((rows, columns))

lst = blist

counts1 = 0
for statement in statements:
    counts2 = 0
    for word in lst:
        if word in statement:
            matrix[counts1, counts2] = 1
        counts2 += 1 
    counts1 += 1 

print(matrix[0])

[1. 1. 1. ... 0. 0. 0.]


In [85]:
#An example for a smaller matrix

lst = ["words", "that", "can", "occur", "in", "a","statement"]
example_statements =[["a", "statement", "with", "words"], ["this", "is", "another", "example", "statement"], 
                     ["and","that", "was", "the", "last", "one"]]

example_matrix = np.zeros((len(example_statements), len(lst)))

ex_counts1 = 0
for statement in example_statements:
    ex_counts2 = 0
    for word in lst:
        if word in statement:
            example_matrix[ex_counts1, ex_counts2] = 1
        ex_counts2 += 1 
    ex_counts1 += 1 
    

print(example_matrix)

[[1. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]]


['that', 'can']